import { z } from 'zod';
const text=z.string().max(20000);
const metric=z.number().int().nonnegative().max(1000000000).nullable();
export const assetSchema=z.object({id:z.string().min(1).max(100),version:z.number().int().positive(),title:z.string().min(1).max(200),audience:z.enum(['Parents','Adults','Both','Schools']),format:z.enum(['Social post','Carousel','Video script','Outreach email']),day:z.number().int().min(1).max(7),english:text,tamil:text,brief:text,claims:text,missing:text,tamilReviewed:z.boolean(),factsReviewed:z.boolean(),approved:z.boolean(),published:text,publishedDate:z.string().max(10),metrics:z.object({reach:metric,responses:metric,clicks:metric,installs:metric,sent:metric,replies:metric,positiveReplies:metric,start:z.string().max(10),end:z.string().max(10),source:z.string().max(500)})});
export const brandSchema=z.object({url:z.string().max(2000).refine(v=>!v||/^https?:\/\//i.test(v),'Use an http or https URL'),features:text,voice:z.string().max(2000),market:z.string().max(500),evidence:text});
export const stateSchema=z.object({revision:z.number().int().nonnegative(),brand:brandSchema,assets:z.array(assetSchema).max(100),review:text});
export type Asset=z.infer<typeof assetSchema>;
export type StudioState=z.infer<typeof stateSchema>;
export const blankMetrics=()=>({reach:null,responses:null,clicks:null,installs:null,sent:null,replies:null,positiveReplies:null,start:'',end:'',source:''});
export function ready(a:Asset){return !!a.english.trim()&&(!a.tamil.trim()||a.tamilReviewed)&&a.factsReviewed&&!a.missing.trim()&&!/\[[^\]]+\]/.test(a.english+' '+a.tamil)}
export function status(a:Asset){return a.published?'Published / sent':a.approved?'Approved':'Needs review'}
export const initialState:StudioState={revision:0,brand:{url:'',features:'',market:'',voice:'Warm, practical and welcoming. Simple Tamil and English. No parental guilt or fluency promises.',evidence:'E01: Product name is miABCTamil. Source: owner conversation; public promotion permitted.\nE02: Tamil-learning app. Source: owner conversation; broad description only.\nE03: Intended audience includes children and adults. Source: owner conversation; specific ages and levels unverified.'},assets:[
{id:'P01',version:1,title:'Which Tamil word would you share first?',audience:'Parents',format:'Carousel',day:1,english:'Slide 1: Which Tamil word would you share first?\nSlide 2: A greeting. A favourite food. A word you use at home.\nSlide 3: Choose one word and say it together.\nSlide 4: What word would you choose? Share it below.\n\nCaption: What is one Tamil word you would love to share with your child? Choose something from everyday life and say it together. Share your word below.',tamil:'உங்கள் குழந்தைக்கு முதலில் எந்தத் தமிழ்ச் சொல்லைச் சொல்லித் தர விரும்புகிறீர்கள்?\n\nஒரு வாழ்த்துச் சொல். பிடித்த உணவின் பெயர். வீட்டில் அடிக்கடி பயன்படுத்தும் ஒரு சொல்.\n\nஒரு சொல்லைத் தேர்ந்தெடுத்து, சேர்ந்து சொல்லிப் பாருங்கள்.\n\nநீங்கள் எந்தச் சொல்லைத் தேர்ந்தெடுப்பீர்கள்? கீழே பகிருங்கள்.',brief:'Four slides, one idea per slide. Large Tamil text, real brand assets. No invented app screens. Alt text: Cards inviting parents to choose an everyday Tamil word to say with their child.',claims:'General learning activity, not an app feature claim. E01 for miABCTamil branding.',missing:'',tamilReviewed:false,factsReviewed:false,approved:false,published:'',publishedDate:'',metrics:blankMetrics()},
{id:'A01',version:1,title:'Start with a hello',audience:'Adults',format:'Video script',day:3,english:'0–4s: Want to start learning Tamil? Start with a hello.\n4–10s: Vanakkam. A Tamil greeting. On-screen: வணக்கம் · Hello.\n10–16s: Say it aloud: vanakkam.\n16–20s: miABCTamil, a Tamil-learning app.\n\nCaption: One word to begin: வணக்கம் — hello. Say it aloud and give yourself a starting point.',tamil:'0–4s: தமிழ் கற்க விரும்புகிறீர்களா? ஒரு வணக்கத்துடன் தொடங்குங்கள்.\n4–10s: வணக்கம். தமிழில் ஒருவரை வாழ்த்தப் பயன்படும் சொல்.\n10–16s: நீங்களும் சொல்லிப் பாருங்கள்: வணக்கம்.\n16–20s: miABCTamil, தமிழ் கற்க ஓர் செயலி.',brief:'20-second text-led video. Fluent speaker to record or approve pronunciation. This is a script; create and review the video before publishing.',claims:'E01, E02. General greeting example requires language review; not represented as an app lesson.',missing:'',tamilReviewed:false,factsReviewed:false,approved:false,published:'',publishedDate:'',metrics:blankMetrics()},
{id:'B01',version:1,title:'What would you like to say in Tamil?',audience:'Both',format:'Social post',day:5,english:'What would you like to say in Tamil?\n\nSay hello · Talk with family · Order a favourite food\n\nIf you are learning Tamil—or choosing a starting point for your child—which would you pick first? Tell us your choice.',tamil:'தமிழில் என்ன பேச விரும்புகிறீர்கள்?\n\nவணக்கம் சொல்ல · குடும்பத்துடன் பேச · பிடித்த உணவை ஆர்டர் செய்ய\n\nஉங்கள் விருப்பத்தைச் சொல்லுங்கள்.',brief:'Question card with three clear text options. Do not label these as app modules.',claims:'E01 for branding only. Proposed interests are not product features.',missing:'',tamilReviewed:false,factsReviewed:false,approved:false,published:'',publishedDate:'',metrics:blankMetrics()},
{id:'O01',version:1,title:'School introduction',audience:'Schools',format:'Outreach email',day:6,english:'Subject: Tamil learning at [School name]\n\nHello [Name],\n\nI’m [Sender name], [Role] at miABCTamil, a Tamil-learning app intended for children and adults.\n\n[Verified reason this school is relevant.]\n\nI’d like to understand your school’s Tamil-learning priorities and whether miABCTamil might be relevant. Would you be open to a brief introductory conversation?\n\nBest,\n[Sender name]\n[Contact details]\n\nFOLLOW-UP DRAFT: Following up on my note about miABCTamil. If Tamil learning is a current priority, I’d welcome a brief conversation. If this is not relevant, I’ll leave it here.',tamil:'',brief:'Personalize from verified recipient information. Send only the introduction first; at most one follow-up if appropriate. Draft only, no sending connection.',claims:'E01–E03. Sender must actually represent miABCTamil.',missing:'Recipient, sender, role, contact details and verified relevance.',tamilReviewed:false,factsReviewed:false,approved:false,published:'',publishedDate:'',metrics:blankMetrics()}
],review:''};
export const campaignPrompt='Create a seven-day miABCTamil campaign with three bilingual social assets and one English school outreach draft. Use the supplied brand evidence only. Give every item one CTA, a visual brief, evidence IDs and missing inputs. Never invent features, results, testimonials, partnerships or pricing. Mark all Tamil for fluent review. Do not send or publish.';
