import {env} from 'cloudflare:workers';
import {z} from 'zod';
import {identity,failure} from '@/lib/studio-server';
import {brandSchema,blankMetrics,stateSchema} from '@/lib/studio-model';
import {instructions} from '@/lib/agent-instructions';
const bodySchema=z.object({kind:z.enum(['campaign','outreach','review']),audience:z.enum(['Parents','Adults','Both','Schools']),topic:z.string().min(1).max(2000),brand:brandSchema,assets:stateSchema.shape.assets.optional()});
const draft=z.object({title:z.string().min(1).max(200),audience:z.enum(['Parents','Adults','Both','Schools']),format:z.enum(['Social post','Carousel','Video script','Outreach email']),day:z.number().int().min(1).max(7),english:z.string().min(1).max(20000),tamil:z.string().max(20000),brief:z.string().max(20000),claims:z.string().max(20000),missing:z.string().max(20000)});
export async function POST(r:Request){try{await identity(r);const raw=await r.text();if(raw.length>1800000)return Response.json({error:'Request is too large.'},{status:413});const parsed=bodySchema.safeParse(JSON.parse(raw));if(!parsed.success)return Response.json({error:'Check the campaign inputs and try again.'},{status:400});const {kind,audience,topic,brand,assets}=parsed.data;
const key=env.ANTHROPIC_API_KEY?.trim() || process.env.ANTHROPIC_API_KEY?.trim();
const model=env.ANTHROPIC_MODEL?.trim() || process.env.ANTHROPIC_MODEL?.trim() || 'claude-sonnet-4-6';
if(!key)return Response.json({error:'Content generation is not available yet. Please contact the studio owner.'},{status:503,headers:{'Cache-Control':'no-store'}});
const shape='Return ONLY a JSON object with an assets array. Each asset has title, audience (Parents|Adults|Both|Schools), format (Social post|Carousel|Video script|Outreach email), day (integer 1–7), english (complete copy), tamil (complete equivalent copy; empty only for English outreach), brief (visual direction and production notes), claims (evidence IDs with explanation), missing (unresolved factual inputs or empty string). All fields except day are strings. Create 3 assets for a campaign, or 1 for outreach. Include timestamped shots for videos and slide copy for carousels. Do not include approval labels in public copy. Never put missing language/owner review in the missing field; those have separate controls.';
const prompt=kind==='review'?'Review the supplied real campaign records. Return a plain-text weekly report with coverage, observations, uncertainty and one next experiment. Never invent numbers.':shape;
const response=await fetch('https://api.anthropic.com/v1/messages',{method:'POST',headers:{'Content-Type':'application/json','x-api-key':key,'anthropic-version':'2023-06-01'},body:JSON.stringify({model,max_tokens:6500,system:instructions+'\n\n'+prompt,messages:[{role:'user',content:JSON.stringify({task:kind,audience,topic,brand,results:kind==='review'?assets:undefined})}]}),signal:AbortSignal.timeout(90000)});
if(!response.ok){const msg=response.status===401?'Content generation is temporarily unavailable. Please contact the studio owner.':response.status===429?'Content generation is busy or temporarily unavailable. Please try again later.':response.status===404?'Content generation is temporarily unavailable. Please contact the studio owner.':'Claude could not complete the request. Your existing drafts are unchanged.';return Response.json({error:msg},{status:502});}
const result=await response.json() as {content?:{type:string,text?:string}[],stop_reason?:string};if(result.stop_reason==='max_tokens')return Response.json({error:'Claude reached its output limit. Try a narrower topic.'},{status:502});const output=result.content?.filter(c=>c.type==='text').map(c=>c.text||'').join('\n')||'';if(!output.trim())return Response.json({error:'Claude returned no draft text. Try again.'},{status:502});if(kind==='review')return Response.json({review:output},{headers:{'Cache-Control':'no-store'}});
let json:unknown;try{json=JSON.parse(output.replace(/^```(?:json)?\s*/,'').replace(/\s*```$/,''))}catch{return Response.json({error:'Claude returned an unreadable draft format. Try again; existing work is safe.'},{status:502})}
const validated=z.object({assets:z.array(draft).min(1).max(4)}).safeParse(json);if(!validated.success)return Response.json({error:'Claude returned an incomplete campaign. Try again with a more specific topic.'},{status:502});return Response.json({assets:validated.data.assets.map(a=>({...a,id:crypto.randomUUID(),version:1,approved:false,tamilReviewed:false,factsReviewed:false,published:'',publishedDate:'',metrics:blankMetrics()}))},{headers:{'Cache-Control':'no-store'}});
}catch(e){if(e instanceof SyntaxError)return Response.json({error:'Invalid request.'},{status:400});if(e instanceof Error&&(e.name==='TimeoutError'||e.name==='AbortError'))return Response.json({error:'Claude took too long to respond. Try again; your existing work is safe.'},{status:504});return failure(e)}}
